package cn.com.winning.ssgj.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-05T10:07:44.684+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.demo.chensj.org/services/hello", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebMethod
    @RequestWrapper(localName = "welcome", targetNamespace = "http://www.demo.chensj.org/services/hello", className = "cn.com.winning.ssgj.ws.client.Welcome")
    @ResponseWrapper(localName = "welcomeResponse", targetNamespace = "http://www.demo.chensj.org/services/hello", className = "cn.com.winning.ssgj.ws.client.WelcomeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String welcome(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
