package cn.com.winning.ssgj.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-05T10:07:44.727+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "HelloWSService", 
                  wsdlLocation = "http://localhost:9999/service/hello?wsdl",
                  targetNamespace = "http://www.demo.chensj.org/services/hello") 
public class HelloWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.demo.chensj.org/services/hello", "HelloWSService");
    public final static QName HelloWSPort = new QName("http://www.demo.chensj.org/services/hello", "HelloWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9999/service/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9999/service/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSPort")
    public HelloWS getHelloWSPort() {
        return super.getPort(HelloWSPort, HelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSPort")
    public HelloWS getHelloWSPort(WebServiceFeature... features) {
        return super.getPort(HelloWSPort, HelloWS.class, features);
    }

}
